# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
language: 'en-uk'

# Website info
name: 'Botbie Blog'
description: 'Your mind is for having ideas, not holding them...'

google_analytics: UA-51088846-5
disqus: botbie-io-blog
facebook_app_id: 1555729331387875

url: http://blog.botbie.io
logo: /assets/images/botbie.png
cover: /assets/images/covers/cover1.jpg
comments: true
navigation: true

# Permalinks
permalink: /:year/:month/:day/:title

# gems and other configs
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# exclude files
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - circle.yml
  - scripts

# paginate
paginate: 5
paginate_path: '/page/:num/'
paginate_tag_basepath: '/tag/:name/'
paginate_tag_layout: 'tag.html'
paginate_author_basepath: '/author/:name/'
paginate_author_layout: 'author.html'
