# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Botbie Blog'
description: "Lãng du đi vô định cánh trym trời"

# Author's info
author: 'Thien Le'
# edit 'categories' in the front matter of every post to match this username
nickname: nguquen
bio: 'Ngủ để mà quên...'
location: 'Nowhere'
image: 'assets/images/casper.png'

google_analytics: UA-69281367-1
disqus: botbie

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - circle.yml
  - scripts
