# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Botbie Blog'
description: "Lãng du đi vô định cánh trym trời"

google_analytics: UA-69281367-1
disqus: botbie

# Permalinks
permalink: /:year/:month/:day/:title

# gems and other configs
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# exclude files
exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - circle.yml
  - scripts

# paginate
paginate: 9
paginate_path: '/page/:num/'
paginate_tag_basepath: '/tag/:name/'
paginate_tag_layout: 'tag.html'
paginate_author_basepath: '/author/:name/'
paginate_author_layout: 'author.html'
