environment: &default_env
  BUNDLE_PATH: vendor/bundle
  USER_NAME: nguquen
  USER_EMAIL: thienlduc@gmail.com
  ORIGIN_URL: git@github.com:botbie/botbie.github.io.git

cached_key: &cached_key blog-bundle-cached-{{ checksum "Gemfile.lock" }}

default_job: &default_job
  environment:
    <<: *default_env
  working_directory: ~/blog
  docker:
    - image: circleci/ruby:2.4.2-jessie-node

version: 2
jobs:
  build:
    <<: *default_job
    steps:
      - checkout
      - restore_cache:
          key: *cached_key
      - run: bundle check || bundle install
      - save_cache:
          key: *cached_key
          paths:
            - vendor/bundle
      - run: bundle exec jekyll build
  deploy:
    <<: *default_job
    steps:
      - checkout
      - restore_cache:
          key: *cached_key
      - run: bundle exec jekyll build
      - add-ssh-keys:
          fingerprints:
            - "SHA256:aeyNGCt4RUekdPWs0v1QvzdhB56lF5Fuj2nAlmGb18s"
      - run: ./scripts/deploy.sh

# workflows
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
